[package]
name = "token-ngrams"
version = "0.1.4"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[lib]
name = "token_ngrams"

[dependencies]
tokenizer = { git = "https://bitbucket.org/swizard/tokenizer.git" }
